CREATE TABLE car_rental.verification_codes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    client_id  BIGINT                                  NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id)
);

ALTER TABLE car_rental.verification_codes
    ADD CONSTRAINT uc_verification_codes_code UNIQUE (code);

ALTER TABLE car_rental.verification_codes
    ADD CONSTRAINT FK_VERIFICATION_CODES_ON_CLIENT FOREIGN KEY (client_id) REFERENCES car_rental.client (id);