create table car_model
(
    year_of_issue integer,
    id_model      bigint generated by default as identity
        primary key,
    body_type     varchar(255),
    brand         varchar(255) not null,
    car_class     varchar(255),
    model         varchar(255) not null
);

alter table car_model
    owner to postgres;

create table car_state
(
    id     bigint generated by default as identity
        primary key,
    name   varchar(255) not null
        unique,
    status varchar(255) not null
        constraint uk6adrvcqcbr8qsi9ak3xcg4mac
            unique
);

alter table car_state
    owner to postgres;

create table car
(
    rent       double precision,
    id         bigint generated by default as identity
        primary key,
    model_id   bigint       not null
        constraint fkdr4movr77cm8s34r8jtv9ajvi
            references car_model,
    state_id   bigint       not null
        constraint fkr7ylxgrplnijyxbh6lkn1eisl
            references car_state,
    gos_number varchar(255) not null
        unique,
    image_url  varchar(255),
    vin        varchar(255) not null
        unique
);

alter table car
    owner to postgres;

create table doctype
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        unique
);

alter table doctype
    owner to postgres;

create table rental_state
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        unique
);

alter table rental_state
    owner to postgres;

create table role
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        unique
);

alter table role
    owner to postgres;

create table client
(
    id         bigint generated by default as identity
        primary key,
    role_id    bigint
        constraint fkt3u054dm7xwantyiihf73p2tj
            references role,
    email      varchar(255) not null
        unique,
    first_name varchar(255) not null,
    last_name  varchar(255),
    login      varchar(255) not null
        unique,
    password   varchar(255) not null,
    phone      varchar(255) not null
        unique
);

alter table client
    owner to postgres;

create table contract
(
    data_end   date,
    data_start date,
    total_cost double precision not null,
    car_id     bigint           not null
        constraint fkixovqbw2hcpmeuelx4a7la9td
            references car,
    client_id  bigint           not null
        constraint fklhq3p3xl25vvnfvyfc51ica0j
            references client,
    id         bigint generated by default as identity
        primary key,
    state_id   bigint           not null
        constraint fk1imu9u0vjfpxljn0keruwa2yi
            references rental_state
);

alter table contract
    owner to postgres;

create table document
(
    date_of_issue     date,
    client_id         bigint not null
        unique
        constraint fk4wiqnj5twgx3pup933cy9yybd
            references client,
    doctype_id        bigint
        constraint fknbwb2oicy6xhsnpu7naufy4x6
            references doctype,
    id                bigint generated by default as identity
        primary key,
    issuing_authority varchar(255),
    number            varchar(255),
    series            varchar(255)
);

alter table document
    owner to postgres;

