CREATE TABLE car_rental.favorite
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id BIGINT                                  NOT NULL,
    car_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_favorite PRIMARY KEY (id)
);

ALTER TABLE car_rental.favorite
    ADD CONSTRAINT FK_FAVORITE_ON_CAR FOREIGN KEY (car_id) REFERENCES car_rental.car (id);

ALTER TABLE car_rental.favorite
    ADD CONSTRAINT FK_FAVORITE_ON_CLIENT FOREIGN KEY (client_id) REFERENCES car_rental.client (id);