CREATE TABLE car_rental.images
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name VARCHAR(255),
    url       VARCHAR(255),
    car_id    BIGINT,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

ALTER TABLE car_rental.images
    ADD CONSTRAINT FK_IMAGES_ON_CAR FOREIGN KEY (car_id) REFERENCES car_rental.car (id);

ALTER TABLE car_rental.car DROP IF EXISTS image_url